import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {X,Download,ArrowUpRight} from 'lucide-react'
import {scripts} from './scriptData'
import {ScriptContent} from './ScriptModal'
import WorkDetails from './components/WorkDetails'
function ScriptReader({initial}){const [id,setId]=useState(initial||scripts[0].id);const script=scripts.find(s=>s.id===id)||scripts[0];return <div className="script-reader condensed-reader"><div className="script-tabs" role="tablist" aria-label="Creative scripts">{scripts.map(s=><button role="tab" aria-selected={s.id===script.id} key={s.id} onClick={()=>setId(s.id)}>{s.title}</button>)}</div><ScriptContent key={script.id} project={script}/></div>}
function Sources(){return <div className="source-reader"><small>CREATIVE SOURCES</small><h2>From observation<br/>to a first frame.</h2><p className="source-intro">A creative process grounded in game features, player preferences, campaign objectives, and the way people watch.</p><div>{[['01','Research & insight','UNDERSTAND','Track creative trends, competitor campaigns, and high-performing content across markets.'],['02','Concept & direction','DEFINE','Translate the brief, product positioning, and audience needs into a clear creative concept.'],['03','Script & storyboard','DEVELOP','Build scene direction, dialogue, visual references, and a production-ready storyboard.'],['04','Production & iteration','DELIVER','Coordinate production and reviews, maintain quality, and use performance feedback to inform the next iteration.']].map(([n,title,label,text])=><article key={n}><span>{n}</span><div><small>{label}</small><h3>{title}</h3><p>{text}</p></div></article>)}</div></div>}
export default function ProjectModal({item,onClose}){const ref=useRef();useEffect(()=>{const previous=document.activeElement;const playing=[...document.querySelectorAll('video')].filter(v=>!v.paused&&!ref.current.contains(v));playing.forEach(v=>v.pause());ref.current.showModal();const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=oldOverflow;playing.forEach(v=>{if(v.isConnected&&v.dataset.background==='true')v.play().catch(()=>{})});previous?.focus()}},[]);return createPortal(<dialog className={`project-modal ${item.kind==='scripts'?'condensed-modal':item.kind?'reader-modal':''}`} ref={ref} aria-label={item.name||'Creative process'} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal-panel"><button className="modal-close" autoFocus onClick={onClose} aria-label="Close details"><X size={23}/></button>{item.kind==='scripts'?<ScriptReader initial={item.script}/>:item.kind==='sources'?<Sources/>:<WorkDetails key={item.video||item.name} item={item}/> }</div></dialog>,document.body)}

